### ISSUE TITLE
Extract files in .png instead of .mni?

### ISSUE THREAD

**Issue by Xe** [Malvineous/camoto-studio#5]
Hello,

I am trying to extract data out of Cosmo's Cosmic Adventure in .png format so I can clean up the tiles and plunk them into tiled. I can't seem to extract data out of cosmo in a standard .png file. How do I do this?

**Comment by Malvineous** [comment]
If you double-click to open the file, then use the toolbar buttons to set your preferred width for the image (how many tiles wide look best) then there should be a toolbar button to export as .png.  There's also another button to import the .png again after you have made your changes to get them back into the game.
